// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Calculator = function(initialValue) {
	this.value = initialValue;
};
Calculator.prototype = {
	add: function(n) {
		this.value += n;
	}
	,multiply: function(n) {
		this.value *= n;
	}
	,getResult: function() {
		return this.value;
	}
};
var Main = function() { };
Main.main = function() {
	var calc = new Calculator(10);
	console.log("Main.hx:24:","Начальное значение: 10");
	calc.add(5);
	console.log("Main.hx:27:","добавили 5");
	calc.multiply(3);
	console.log("Main.hx:30:","умножили на 3");
	console.log("Main.hx:32:","---");
	console.log("Main.hx:33:","Итоговый результат: " + calc.getResult());
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
