# Generated by Haxe 4.3.7
# coding: utf-8
import sys



class AppInfo:
    __slots__ = ("buildVersion", "buildTime")

    def __init__(self):
        self.buildTime = "2025-11-15 10:24:23"
        self.buildVersion = "1.0.0-alpha"



class Demo2:
    __slots__ = ()

    @staticmethod
    def main():
        print("\n--- Демо 2: Макросы ---")
        app = AppInfo()
        print(str(("Версия сборки: " + HxOverrides.stringOrNull(app.buildVersion))))
        print(str(("Время сборки: " + HxOverrides.stringOrNull(app.buildTime))))


class haxe_iterators_ArrayIterator:
    __slots__ = ("array", "current")

    def __init__(self,array):
        self.current = 0
        self.array = array

    def hasNext(self):
        return (self.current < len(self.array))

    def next(self):
        def _hx_local_3():
            def _hx_local_2():
                _hx_local_0 = self
                _hx_local_1 = _hx_local_0.current
                _hx_local_0.current = (_hx_local_1 + 1)
                return _hx_local_1
            return python_internal_ArrayImpl._get(self.array, _hx_local_2())
        return _hx_local_3()



class python_internal_ArrayImpl:
    __slots__ = ()

    @staticmethod
    def _get(x,idx):
        if ((idx > -1) and ((idx < len(x)))):
            return x[idx]
        else:
            return None


class HxOverrides:
    __slots__ = ()

    @staticmethod
    def stringOrNull(s):
        if (s is None):
            return "null"
        else:
            return s


class python_internal_MethodClosure:
    __slots__ = ("obj", "func")

    def __init__(self,obj,func):
        self.obj = obj
        self.func = func

    def __call__(self,*args):
        return self.func(self.obj,*args)




Demo2.main()
