// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var AppInfo = function() {
	this.buildTime = "2025-11-15 10:23:36";
	this.buildVersion = "1.0.0-alpha";
};
var Demo2 = function() { };
Demo2.main = function() {
	console.log("Demo2.hx:6:","\n--- Демо 2: Макросы ---");
	var app = new AppInfo();
	console.log("Demo2.hx:12:","Версия сборки: " + app.buildVersion);
	console.log("Demo2.hx:13:","Время сборки: " + app.buildTime);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Demo2.main();
})({});
